/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SerendipityPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var SerendipitySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    let { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Source Directory").setDesc('The directory from which to pick a random file from. If specified, "exclude directory" will be ignored').addText((text) => text.setPlaceholder("Enter the directory name. e.g. Journal, or Books").setValue(this.plugin.settings.sourceDirectory).onChange(async (value) => {
      this.plugin.settings.sourceDirectory = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Exclude Directory").setDesc('The directory to exclude from the random file picker. This will be ignored if "source directory" is specified').addText((text) => text.setPlaceholder("Enter the directory name e.g. Work, Drafts").setValue(this.plugin.settings.excludeDirectory).onChange(async (value) => {
      this.plugin.settings.excludeDirectory = value;
      await this.plugin.saveSettings();
    }));
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  sourceDirectory: "",
  excludeDirectory: ""
};
var SerendipityPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.onAppOpen = async () => {
      const randomMdFile = await this.getRandomEntry();
      if (randomMdFile) {
        new SerendipityModal(this.app, randomMdFile).open();
      }
    };
  }
  async onload() {
    await this.loadSettings();
    this.app.workspace.onLayoutReady(this.onAppOpen);
    this.addSettingTab(new SerendipitySettingTab(this.app, this));
  }
  onunload() {
  }
  async getRandomEntry() {
    let mdFilesInVault;
    const sourceDirectory = this.app.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(this.settings.sourceDirectory));
    const excludeDirectory = this.app.vault.getFolderByPath((0, import_obsidian2.normalizePath)(this.settings.excludeDirectory));
    if (!sourceDirectory || !(sourceDirectory instanceof import_obsidian2.TFolder)) {
      new import_obsidian2.Notice("Invalid source directory. Checking for excluded directory instead");
      mdFilesInVault = this.app.vault.getMarkdownFiles();
      if (!excludeDirectory || !(excludeDirectory instanceof import_obsidian2.TFolder)) {
        new import_obsidian2.Notice("Invalid exclude directory. Using all of the vault as source");
      } else {
        new import_obsidian2.Notice(`Excluding files from ${this.settings.excludeDirectory} directory`);
        mdFilesInVault = mdFilesInVault.filter((file) => !file.path.startsWith(this.settings.excludeDirectory));
      }
    } else {
      mdFilesInVault = sourceDirectory.children.filter((file) => file instanceof import_obsidian2.TFile && file.extension === "md");
    }
    if (mdFilesInVault.length === 0) {
      new import_obsidian2.Notice("No markdown files found in the specified directory");
      return null;
    }
    const randomIndex = Math.floor(Math.random() * mdFilesInVault.length);
    return mdFilesInVault[randomIndex];
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SerendipityModal = class extends import_obsidian2.Modal {
  constructor(app, file) {
    super(app);
    this.file = file;
  }
  async onOpen() {
    const { containerEl, contentEl } = this;
    const fileContents = this.file instanceof import_obsidian2.TFile ? await this.app.vault.read(this.file) : "";
    containerEl.addClass("serendipity-modal-container");
    const header = contentEl.createDiv({ cls: "modal-header" });
    const openCta = new import_obsidian2.ButtonComponent(header);
    openCta.setButtonText("Open in vault").onClick(() => {
      this.file instanceof import_obsidian2.TFile && this.app.workspace.getLeaf("tab").openFile(this.file);
      this.close();
    });
    const closeCta = new import_obsidian2.ButtonComponent(header);
    closeCta.setButtonText("Close").onClick(() => {
      this.close();
    });
    const contentContainer = contentEl.createDiv({ cls: "markdown-preview" });
    this.component = new import_obsidian2.Component();
    import_obsidian2.MarkdownRenderer.render(this.app, fileContents, contentContainer, this.file.path, this.component);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.component.unload();
  }
};
