/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CustomNewFileNamePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  fileNameFormat: "Untitled {{datetime:YYYYMMDDHHmmss}}"
};
var CustomNewFileNamePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new CustomNewFileNameSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        menu.addItem((item) => {
          item.setTitle("New note (with custom name)").onClick(() => {
            this.createNewFile(file);
          });
        });
      })
    );
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async createNewFile(menuFile) {
    const dir = menuFile instanceof import_obsidian.TFile ? menuFile.parent : menuFile;
    if (dir == null) {
      return;
    }
    try {
      const dirPath = dir.parent == null ? "" : dir.path + "/";
      const filename = this.createFileName();
      const filePath = this.getAvailableFilePath(dirPath + filename, ".md");
      const file = await this.app.vault.create(filePath, "");
      await this.app.workspace.getLeaf().openFile(file);
    } catch (e) {
      new import_obsidian.Notice("Failed to create new file: " + e.toString());
    }
  }
  getFileNameFormat() {
    return this.settings.fileNameFormat || DEFAULT_SETTINGS.fileNameFormat;
  }
  createFileName() {
    const format = this.getFileNameFormat();
    const datetimePattern = /\{\{datetime:(.*?)\}\}/;
    const match = format.match(datetimePattern);
    if (!match) {
      return format;
    }
    const dateFormat = match[1];
    const formattedDatetime = (0, import_obsidian.moment)().format(dateFormat);
    return format.replace(datetimePattern, formattedDatetime);
  }
  getAvailableFilePath(basePath, ext) {
    let path = basePath + ext;
    let i = 1;
    while (this.app.vault.getAbstractFileByPath(path) != null) {
      path = basePath + " " + i + ext;
      i++;
    }
    return path;
  }
};
var CustomNewFileNameSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("New file name format").setDesc('Define the format for new file names. You can use "{{datetime:YYYYMMDDHHmmss}}" to include the current date and time in your format.').addText((text) => text.setPlaceholder(DEFAULT_SETTINGS.fileNameFormat).setValue(this.plugin.settings.fileNameFormat).onChange(async (value) => {
      this.plugin.settings.fileNameFormat = value;
      await this.plugin.saveSettings();
    }));
  }
};
